name: skoreio
description: A Flutter project for SkoreIO test.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  shimmer: ^1.1.2
  intl: ^0.16.1
  get: ^3.10.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # Material Icons font
  uses-material-design: true

  # Assets
  assets:
    - assets/data/
    - assets/icons/
    - assets/images/

  # Fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunitoregular.ttf
        - asset: assets/fonts/nunitoitalic.ttf
          style: italic
        - asset: assets/fonts/nunitobold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserratregular.ttf
        - asset: assets/fonts/montserratbold.ttf
          weight: 700